# Generated by Django 5.0.6 on 2024-07-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
    ]
