# Generated by Django 5.0.6 on 2024-08-04 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_answer_voter_question_voter_alter_answer_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='down_voter',
            field=models.ManyToManyField(related_name='down_voter_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='down_voter',
            field=models.ManyToManyField(related_name='down_voter_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
