# Generated by Django 5.0.6 on 2024-08-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link_name',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
